services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mydb}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  myapp:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:${DB_PORT:-5432}/${DB_NAME:-mydb}
      QUARKUS_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      QUARKUS_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgres}
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
    ports:
      - "${APP_PORT:-8080}:8080"
    command: ["java", "-jar", "/work/quarkus-run.jar"]

volumes:
  pgdata:
